// Generated by CoffeeScript 1.7.1
(function() {
  var absValue, absValueToo, add, add2, allAbsValue, onlyPositive, person, sumAll, sumArray, sumPartArray, withinRange,
    __slice = [].slice;

  add2 = function(x) {
    return x + 2;
  };

  console.log(add2(2));

  add = function(x, y) {
    return x + y;
  };

  console.log(add(4, 5));

  add = function(x, y) {
    if (y == null) {
      y = 1;
    }
    return x + y;
  };

  absValue = function(x) {
    if (x < 0) {
      return -x;
    } else {
      return x;
    }
  };

  withinRange = function(x, lower, upper) {
    if (x <= upper && x >= lower) {
      return true;
    } else {
      return false;
    }
  };

  absValueToo = function(x) {
    if (x < 0) {
      x = -x;
    }
    return x;
  };

  allAbsValue = function(arr) {
    var item, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = arr.length; _i < _len; _i++) {
      item = arr[_i];
      _results.push(absValue(item));
    }
    return _results;
  };

  onlyPositive = function(arr) {
    var elem, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = arr.length; _i < _len; _i++) {
      elem = arr[_i];
      if (elem > 0) {
        _results.push(elem);
      }
    }
    return _results;
  };

  person = function(name, city) {
    return {
      name: name,
      city: city
    };
  };

  sumArray = function(arr) {
    var number, sum, _i, _len;
    sum = 0;
    for (_i = 0, _len = arr.length; _i < _len; _i++) {
      number = arr[_i];
      sum += number;
    }
    return sum;
  };

  sumPartArray = function(arr, lower, upper) {
    var number, sum, _i, _len, _ref;
    sum = 0;
    _ref = arr.slice(lower, +upper + 1 || 9e9);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      number = _ref[_i];
      sum += number;
    }
    return sum;
  };

  sumAll = function() {
    var item, number, rest, sum, _i, _len;
    item = arguments[0], rest = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    sum = item;
    for (_i = 0, _len = rest.length; _i < _len; _i++) {
      number = rest[_i];
      sum += number;
    }
    return sum;
  };

  module.exports.add2 = add2;

  module.exports.add = add;

  module.exports.absValue = absValue;

  module.exports.withinRange = withinRange;

  module.exports.absValueToo = absValueToo;

  module.exports.allAbsValue = allAbsValue;

  module.exports.person = person;

  module.exports.onlyPositive = onlyPositive;

  module.exports.sumArray = sumArray;

  module.exports.sumPartArray = sumPartArray;

  module.exports.sumAll = sumAll;

}).call(this);
