// Generated by CoffeeScript 1.7.1
(function() {
  var add2, assert;

  assert = require('assert');

  add2 = require('./intro').add2;

  describe("testing add2", function() {
    return it("should return 42", function() {
      return assert.equal(add2(40), 42);
    });
  });

}).call(this);
