// Generated by CoffeeScript 1.7.1
(function() {
  exports.formResponse = function(req, res) {
    return res.render('form');
  };

  exports.postResponse = function(req, res) {
    return res.send('You said ' + req.body.text);
  };

}).call(this);
